/* Se describen los comandos de SQL para la creación de tablas

CREATE TABLE table_name(
    column1 data_type NOT NULL PRIMARY KEY,
    column2 data_type,
    column3 data_type FOREIGN KEY REFERENCES table_name(column_ref),
    column4 data_type,
);

*/

CREATE TABLE PROVINCIAS(
    ID_PROVINCIA INT NOT NULL PRIMARY KEY, --DEFINICIÓN DE PRIMARY KEY Y CONDICIÓN NO NULA
    NOMBRE VARCHAR2(100),
    ID_PUEBLO INT FOREIGN KEY REFERENCES PUEBLOS(ID_PUEBLO), --DEFINICIÓN DE FOREIGN KEY
);

CREATE TABLE PUEBLOS(
    ID_PUEBLO INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(200),
    ID_PROVINCIA INT FOREIGN KEY REFERENCES PROVINCIAS(ID_PROVINCIA),
    ID_SOCIO INT FOREIGN KEY REFERENCES SOCIOS(ID_SOCIO),
);

CREATE TABLE LIBROS(
    ID_BOOK INT NOT NULL PRIMARY KEY,
    TITULO VARCHAR2(500),
    AUTOR VARCHAR2(500),
    STOCK INT,
);

CREATE TABLE SOCIOS(
    ID_SOCIO INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    APELLIDOS VARCHAR2(100),
    FECHA_NAC DATE,
    NIF CHAR(9),
    TELF INT,
    EMAIL VARCHAR2(200),
    ID_PUEBLO INT FOREIGN KEY REFERENCES PUEBLOS(ID_PUEBLO),
);


CREATE TABLE PRESTAMOS(
    ID_PRESTAMO INT NOT NULL PRIMARY KEY,
    PRESTADO DATE,
    DEVUELTO DATE,
    ID_BOOK INT FOREIGN KEY REFERENCES LIBROS(ID_BOOK),
    ID_SOCIO INT FOREIGN KEY REFERENCES SOCIOS(ID_SOCIO),
);